
---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local

  tasks:

  - name: "just execute a touch command"
    shell: "touch hello.txt"
    register: "output"

  - debug: var=output.stdout_lines
